# print("D" in "Delhi")
# print(1 in [ 1 , 2, 3, 4, 5])

# number = int(input("Enter the 3 digit number :"))
# a = number % 10   #432 #2
# b = number // 10 
# c = b % 10 #3

# d = number // 100
# sum = a + c + d
# print( "the sum of three digit is " , sum)


# loops in pyhton

# givenEmail = "sid@gmail.com"
# givenPass = 1234

# email = input("Enter the email of the user :")
# password  =  int(input("Enter the password of the user :"))

# if email == givenEmail and password == givenPass :
#   print("User logged in successfully")

# elif email == givenEmail and password != givenPass :
#   print("Invalid Password")
#   newPassword =  int(input('Enter the password again : '))
#   if newPassword == givenPass :
#     print("userlogged in Successfully")

#     exit

#   else :
#     print("You havee succeeded your limit and please try again next day")
    

# else :
#   print("Invalid credentials and User Could not logged In ? Thank You")

# number = int(input("Enter the 3 digit Number :"))
# a = number % 10 # here we will get the first digit of the number from the last

# b = number // 10 # here we will get the last 2 digit 
# c = b % 10  # here we will get the second digit of the number 

# d = number // 100 # here we will get the last digit 

# if a > (d and c ) :
#   print("The greatest Number is : " , a)

# elif d > ( a and c ) :
#     print("The greatest Number is  : " , d)


# else :
#     print("The greatest Number is : " , c)






# import random

# print(random.randint(1 , 45))

# help('modules')


#loops in python....

'''here we are going to print the table of any given number that will be entered by the user'''

# number = int(input("Enter the number :"))
# i = 1
# sum = 0
# while i <=10 :
#    sum += number 
  
#    print(number ,"* ",i ,"=",sum)
#    i = i + 1
   





'''Her we are going to make a guissing game where the user will have to guess the number that is generated by the computer and the user will have 3 chances to guess the number'''

import random 

# jackpot = int(input("Enter the number :" ))
# geneNumber = random.randint(1 , 100)
# print("The generated Number is :",geneNumber)
# '''Now we are defining the logic of this...'''
# if jackpot == geneNumber :
#   print("Congratulations 😱 ->  You have guessed correct Number :")

# elif jackpot != geneNumber :
# for i in range ( 1 , 4 ) :
#     jackpot = int(input("Enter the Number : "))
#     geneNumber = random.randint(1 , 100)
#     print( "The generated Number is : " , geneNumber)

#     if jackpot == geneNumber :
#      print("Congratulations 😱 ->  You have guessed correct Number :")

#     i += 1



'''Current Populaton  of the town is -> 10000
  and it is increasing by 10% every year and we have to find the population after 10 years'''

  #currentPopulation = 10000 

  # currentPopulation -= 0.1*currentPopulation
  # print( i , currentPopulation)




'''Write a program that will give you in hand monthly salary after deduction on CTC ~ HRA(10%) , DAA(5%) PF(3%) and taxes deduction below 
  below 5 : 0%
  5-10 : 10 %
  10-20 : 20 %
  above 20 : 30 %'''


# given_sal = int(input("Enter your Salary :"))
# tax = 0

# if given_sal < 500000 :
#   tax = 0
  

# elif 500000 < given_sal < 1000000 :
#   tax = 0.1*given_sal
  
  
# elif 1000000 < given_sal < 2000000 :
#   tax = 0.2*given_sal
  

# else :
#   tax = 0.3*given_sal
    



# sal_after_ded = given_sal - 0.1*given_sal - 0.05*given_sal - .03*given_sal - tax 
# monthly_salary = sal_after_ded /12 
# print("the monthly salary is :" , monthly_salary)



''' Write a  program that takes a user input of three angles and will find out wheather it can form a triangle or not :'''

# a1 = int(input("Enter first angle :"))
# a2 = int(input("Enter second angle :"))
# a3 = int(input("Enter third angle :"))

# if (a1 + a2 + a3 ) == 180 :
#   print("yes it can form an triangle because all three angle's sum is 180 :")

# else :
#   print("Invalid angles : please enter correct angles :")



'''write a program that will take user input of cost price and selling price and determines wheather its a loss or profit'''

# cost_price = int (input("Enter the cost price :"))
# selling_price = int(input("Enter the selling Price :"))

# if selling_price > cost_price :
#   print("Profit : you can sell it ")

# else :
#   print("loss : Pleas dont sell it :")



'''write a menu driver program'''

# number = int(input("Enter the number :"))
# convert = input("Enter Conversion formate in CM , FT or INR : ")

# if convert not in ("mile" , "inr" , "ft") :
#   print( "Invalid Conversion :")

# if convert == "ft" :
#   ft = number / 12.5
#   print("Total feet are : " , ft)

# elif convert == "mile" :
#   mile = number * 0.6
#   print("Total miles are :", mile)

# elif convert == "inr" :
#   inr = number *90
#   print("Total rupees are : " , inr)



'''fibonacci Series up to 10 terms...'''

# p = int(input("Enter the number "))

# f1 = 1
# f2 = 2
# print(f1)
# print(f2)

# for n in range ( 3 , p + 1) :
#   fn = f1 + f2

#   f1 = f2 
#   f2 = fn

#   print (fn)
   



'''factorial of given Number :'''

# import math
# n = int(input("Enter the factorial number :"))
# fact1 = 1
# for n in range( 1 , n +1):
#   fact1 = n * fact1
  
#   print(fact1)


'''Reverse a given interger Number :'''

# number = (input("Enter number :")) #
# rev = (number)[::-1]

# rev1 = number[3 : 6]
# rev2 = number[-6 : ]
# rev3 = number[6 : 2 : -1 ]

# print(type(rev))
# print(rev)
# print(rev1)
# print(rev2)
# print(rev3)


'''Write a Python program to:

Take an integer N as input from the user.
Find the sum of numbers from 1 to N.
If any number is divisible by 5, skip that number.
If the sum becomes greater than 300, stop the calculation immediately.
Print the final sum.
Do not use a for loop. Solve it using a while loop only.'''

# n = int(input("Enter the number :"))


# i = 1
# total = 0
# while i <= n :
#   if i % 5 == 0 :
#     i += 1
#     continue

#   total += i 
#   i += 1 
#   if total > 300 :
#     print("the sum is greater than 300 :")
#     break

  

# print(total)

''' write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers :''' 

# n = int(input("Enter the number :"))
# sum = n
# for i in range(1 , n) :
#   if n != 0 :
#     n = int(input("Enter the number :"))
#     sum += n
#     print("Total sum is : " , sum)
#     avg = sum /( i+1)
#     print("the average us : " , avg)

#     i+=1 
#     continue

#   else :
   
#     print("you have entered 0 So Exit..")
#     break
    

total = 0
count = 0
while True :
  n = int(input("Enter the number :"))

  if n == 0 :
    break

  total += n
  count += 1
  
    


avg = total / count

print("The total is : " , total)
print("The average is :" , avg)














    
      
    
    


  




    




  

   


  



  



 



  









  